### ISSUE TITLE
【feat】 请教 

### ISSUE THREAD

**Issue by gujinlonghaha** [zzetao/mandy#3]
👏     ███╗   ███╗ █████╗ ███╗   ██╗██████╗ ██╗   ██╗
  ████╗ ████║██╔══██╗████╗  ██║██╔══██╗╚██╗ ██╔╝
  ██╔████╔██║███████║██╔██╗ ██║██║  ██║ ╚████╔╝ 
  ██║╚██╔╝██║██╔══██║██║╚██╗██║██║  ██║  ╚██╔╝  
  ██║ ╚═╝ ██║██║  ██║██║ ╚████║█████╔╝   ██║   
  ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝    ╚═╝               请教大神  1图标  2品牌mandy  分别是拿什么实现的

**Comment by zzetao** [comment]
1. 图标：Emoji
2. 品牌：ASCII 字符画

可以网上搜一下

**Comment by gujinlonghaha** [comment]
男人看了欢呼  女人看了雀跃   非常感谢
